---
output: html_document
---

<center> <h1>2014年12月03日</h1> </center>
<center> <h4>[back to blog](index.html)</h4> </center>

今天主要和亚乐初步搞明白了github上面怎么共同协作。说初步是因为没有涉及到branch，只是master之间的沟通。有些东西还是自己理解了之后才能运用，自己理解的方式和书上讲的还是有很大差别的，或者说这个东西就没什么书讲。

- 两个人协作，两个身份，领导和小弟。每个人又有两个地方，本地电脑和远程托管地。所以，一共涉及四个地方：
    1. **领导的本地**：首先，领导在自己的电脑上搞点初始的
    2. **领导的远程**：然后，领导把开始工作传到（领导的）远程（比如github）
    3. **小弟的远程**：接着，小弟从（小弟的）远程folk领导的远程
    4. **小弟的本地**：最后，小弟从自己的远程clone到自己的本地

- 以上共同开发的环境就创建好了。也就是说，四个地方的文件都同步好了。注意领导与小弟的沟通是通过远程的folk来实现的（当然private repo的话，领导要先share给小弟）。

- 对于以上四个节点，**小弟**需要关心的有三个：**领导的远程**，**小弟的远程**，**小弟的本地**。工作流程为：
    1. （从领导那）接活：**领导的远程**--pull-->**小弟的本地**`小弟本地直接从领导那接活，那小弟远程还有用么？`
    2. 保存到自己的远程：**小弟的本地**--push-->**小弟的远程**
    3. （往领导那）交活：**小弟的远程**--pull request-->**领导的远程**`有用，小弟通过小弟远程来交活（pull request）`【本质：小弟不能直接push到领导那】
    
- 对于以上四个节点，**领导**需要关心的有三个： **小弟的远程**，**领导的远程**，**领导的本地**。工作流程为：
    1. （从小弟那）收活：**小弟的远程**--被merge-->**领导的远程**
    2. 【若上一步无冲突】保存到自己的本地：**领导的远程**--pull-->**领导的本地**
    2. 【若上一步有冲突】保存到自己的本地：**小弟的远程**--pull-->**领导的本地**（手动修改冲突）
    3. 至此，领导的本地是最新版本的文件。

- 以此类推。

- 其实说简单也简单，真正干起活来，就是：
    1. pull最新文件【**领导的远程**-->**小弟的本地**】（用git）
    2. 要有冲突解决冲突【**小弟的本地**】（在干活，吸取别人新代码）
    3. 自己写代码【**小弟的本地**】（在干活，自己写代码）
    4. push到自己的远程【**小弟的本地**-->**小弟的远程**】（用git）
    5. pull request交活【**小弟的远程**-->**领导的远程**】（用git）
这么几件事。

- 一点总结：
    - 想pull，谁都能pull谁。
    - 想push，（自己当然都能push自己），领导没必要push给小弟，小弟不能push给领导（要通过send pull request）。